USE hazina_asili;

-- USERS (7 records)
INSERT INTO `users` (`name`,`email`,`password`,`role`,`bio`,`institution`,`created_at`) VALUES ('System Admin','admin@natcompdb.com','$2y$12$mBSUvl0XCyBoIIuBdxnp.OPn.gMZcQ0DC4dSSJHM9ZzVlpBs6yOAq','admin',NULL,NULL,'2026-04-27 17:10:40');
INSERT INTO `users` (`name`,`email`,`password`,`role`,`bio`,`institution`,`created_at`) VALUES ('Dr. Jane Smith','researcher@natcompdb.com','$2y$12$mBSUvl0XCyBoIIuBdxnp.OPn.gMZcQ0DC4dSSJHM9ZzVlpBs6yOAq','researcher',NULL,NULL,'2026-04-27 17:10:40');
INSERT INTO `users` (`name`,`email`,`password`,`role`,`bio`,`institution`,`created_at`) VALUES ('Simon Masalago','masalagosimon442@gmail.com','$2y$12$8HPXv2Fn5dWl4nbHe4R4SO.88NcVYmUs6NGsksJSjcSHzHIahyT1W','researcher',NULL,NULL,'2026-04-27 17:17:36');
INSERT INTO `users` (`name`,`email`,`password`,`role`,`bio`,`institution`,`created_at`) VALUES ('janeth peter','simonmachibya65@gmail.com','$2y$12$GmSBcaWcj6/Ny42goA2XZ.eRH8nLkyx/mHwKYftqmGPJ0dh8.NFpu','researcher',NULL,NULL,'2026-04-27 17:37:28');
INSERT INTO `users` (`name`,`email`,`password`,`role`,`bio`,`institution`,`created_at`) VALUES ('machibya','josephmasanja955@gmail.com','$2y$12$qh8R1DnfHyDiLGYRSWro3u6AFTrxpubM3IU1d75Sdl5MhuBzDPjX.','admin',NULL,NULL,'2026-04-27 17:38:56');
INSERT INTO `users` (`name`,`email`,`password`,`role`,`bio`,`institution`,`created_at`) VALUES ('Songelael Yoel','songelael@gmail.com','$2y$12$.BMysRmq55bNyogXnVjWd.29xBtRNyysfvy4GajZoFaxm2MFTnaNy','admin',NULL,NULL,'2026-04-28 14:24:32');
INSERT INTO `users` (`name`,`email`,`password`,`role`,`bio`,`institution`,`created_at`) VALUES ('Faith Mabiki','fmabiki@sua.ac.tz','$2y$12$L/sdddpmzta4zxOMdLh/CODxBOtrHKIK7.HQTBlR/cmAHrJBz.wte','admin',NULL,'SUA','2026-04-28 14:57:35');

-- ORGANISMS (19 records)
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida','Ericales','Theaceae','Camellia','sinensis','eukaryotic','Tropical and subtropical regions of Asia',NULL,NULL,'Camellia sinensis');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida','Zingiberales','Zingiberaceae','Curcuma','longa','eukaryotic','Tropical South Asia',NULL,NULL,'Curcuma longa');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida','Asparagales','Amaryllidaceae','Allium','sativum','eukaryotic','Central Asia, widely cultivated worldwide',NULL,NULL,'Allium sativum');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida','Zingiberales','Zingiberaceae','Zingiber','officinale','eukaryotic','Southeast Asia, tropical regions',NULL,NULL,'Zingiber officinale');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Fungi','Ascomycota','Eurotiomycetes','Eurotiales','Aspergillaceae','Penicillium','chrysogenum','eukaryotic','Soil, decaying organic matter, indoor environments',NULL,NULL,'Penicillium chrysogenum');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Bacteria','Actinobacteria','Actinomycetia','Streptomycetales','Streptomycetaceae','Streptomyces','griseus','prokaryotic','Soil worldwide',NULL,NULL,'Streptomyces griseus');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Taxus brevifolia');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Cinchona officinalis');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Papaver somniferum');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Catharanthus roseus');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Artemisia annua');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Camptotheca acuminata');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Glycyrrhiza glabra');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Vitis vinifera');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Piper nigrum');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Capsicum annuum');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Plantae','Tracheophyta','Magnoliopsida',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ephedra sinica');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Fungi','Basidiomycota','Agaricomycetes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ganoderma lucidum');
INSERT INTO `organisms` (`kingdom`,`phylum`,`class`,`order_name`,`family`,`genus`,`species`,`cell_type`,`habitat`,`description`,`structure_image`,`scientific_name`) VALUES ('Bacteria','Actinobacteria','Actinomycetia',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Streptomyces avermitilis');

-- REFERENCES (4 records)
INSERT INTO `references` (`title`,`author`,`year`,`citation`) VALUES ('Quercetin: A Versatile Flavonoid','Boots, A.W., Haenen, G.R., Bast, A.',2008,'Boots AW, Haenen GR, Bast A. Health effects of quercetin. Eur J Pharmacol. 2008;585(2-3):325-37.');
INSERT INTO `references` (`title`,`author`,`year`,`citation`) VALUES ('Curcumin: Biological and Medicinal Properties','Aggarwal, B.B., Harikumar, K.B.',2009,'Aggarwal BB, Harikumar KB. Potential therapeutic effects of curcumin. Int J Biochem Cell Biol. 2009;41(1):40-59.');
INSERT INTO `references` (`title`,`author`,`year`,`citation`) VALUES ('Allicin: Chemistry and Biological Properties','Borlinghaus, J. et al.',2014,'Borlinghaus J et al. Allicin: chemistry and biological properties. Molecules. 2014;19(8):12591-618.');
INSERT INTO `references` (`title`,`author`,`year`,`citation`) VALUES ('Penicillin: Discovery and Development','Fleming, A.',1929,'Fleming A. On the antibacterial action of cultures of a Penicillium. Br J Exp Pathol. 1929;10(3):226-236.');

-- COMPOUNDS (28 records)
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Quercetin','C15H10O7',302.2357,'A plant flavonoid found in many fruits, vegetables, and grains. Known for its antioxidant and anti-inflammatory properties.',NULL,1,NULL,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Curcumin','C21H20O6',368.3799,'The principal curcuminoid of turmeric. Exhibits anti-inflammatory, antioxidant, and potential anticancer properties.',NULL,2,NULL,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Allicin','C6H10OS2',162.2700,'An organosulfur compound obtained from garlic. Responsible for the characteristic odor and many health benefits of garlic.',NULL,3,NULL,2);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Gingerol','C17H26O4',294.3800,'The active constituent of fresh ginger. Exhibits anti-nausea, anti-inflammatory, and antioxidant effects.',NULL,4,NULL,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Penicillin G','C16H18N2O4S',334.3900,'A beta-lactam antibiotic produced by Penicillium fungi. The first widely used antibiotic in clinical medicine.',NULL,5,NULL,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Streptomycin','C21H39N7O12',581.5700,'An aminoglycoside antibiotic produced by Streptomyces griseus. Used to treat tuberculosis and other bacterial infections.',NULL,6,NULL,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Resveratrol','C14H12O3',228.2440,'A stilbenoid found in the skin of red grapes. Associated with cardiovascular protection and anti-aging properties.',NULL,NULL,NULL,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Caffeine','C8H10N4O2',194.1900,'A purine alkaloid found in coffee, tea, and cacao. Acts as a central nervous system stimulant.',NULL,1,NULL,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Paclitaxel (Taxol)','C47H51NO14',853.9060,'A diterpenoid natural product isolated from the Pacific yew tree. One of the most important anticancer drugs ??? it stabilizes microtubules and prevents cell division. Used clinically to treat breast, ovarian, and lung cancers.',NULL,7,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Quinine','C20H24N2O2',324.4170,'An alkaloid found in the bark of Cinchona trees. The first effective treatment for malaria, it acts by interfering with the parasite ability to digest hemoglobin. Also used as a flavoring agent in tonic water.',NULL,8,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Morphine','C17H19NO3',285.3380,'A potent opioid alkaloid found in the opium poppy. The primary active agent in opium, it acts on opioid receptors in the central nervous system to relieve pain. It is the prototype of all opioid analgesics.',NULL,9,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Vincristine','C46H56N4O10',824.9580,'A vinca alkaloid derived from the Madagascar periwinkle. It inhibits mitosis by binding to tubulin and preventing microtubule formation. Widely used in chemotherapy for leukemia and lymphoma.',NULL,10,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Artemisinin','C15H22O5',282.3320,'A sesquiterpene lactone endoperoxide isolated from Artemisia annua (sweet wormwood). The most effective antimalarial drug available, particularly against drug-resistant Plasmodium falciparum. Nobel Prize in Medicine 2015.',NULL,11,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Camptothecin','C20H16N2O4',348.3530,'A cytotoxic quinoline alkaloid isolated from Camptotheca acuminata. It inhibits DNA topoisomerase I, preventing DNA replication. Parent compound of anticancer drugs irinotecan and topotecan.',NULL,12,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Glycyrrhizin','C42H62O16',822.9300,'A triterpenoid saponin and the primary sweet-tasting compound in licorice root. It has anti-inflammatory, antiviral, and hepatoprotective properties. Used in traditional medicine and as a food sweetener.',NULL,13,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Epigallocatechin Gallate (EGCG)','C22H18O11',458.3720,'The most abundant catechin in green tea. A powerful antioxidant with anti-inflammatory, anticancer, and neuroprotective properties. It inhibits cancer cell proliferation and promotes apoptosis.',NULL,1,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Piperine','C17H19NO3',285.3380,'An alkaloid responsible for the pungency of black pepper. It enhances the bioavailability of other compounds, particularly curcumin, by inhibiting drug metabolism enzymes. Also has anti-inflammatory and antidepressant properties.',NULL,15,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Capsaicin','C18H27NO3',305.4120,'The active component of chili peppers responsible for their heat. It binds to TRPV1 receptors causing a burning sensation. Used topically as an analgesic for neuropathic pain and arthritis.',NULL,16,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Ephedrine','C10H15NO',165.2320,'A sympathomimetic alkaloid from Ephedra sinica (ma huang). It stimulates the release of norepinephrine and acts as a bronchodilator. Used historically for asthma and nasal congestion.',NULL,17,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Ganoderic Acid A','C30H44O7',508.6600,'A lanostane-type triterpenoid isolated from Ganoderma lucidum (reishi mushroom). It exhibits anticancer, anti-inflammatory, and hepatoprotective activities. Inhibits cancer cell growth by inducing apoptosis.',NULL,18,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Avermectin B1a','C48H72O14',873.0800,'A macrocyclic lactone produced by Streptomyces avermitilis. A potent antiparasitic agent that enhances GABA-mediated neurotransmission in invertebrates. Parent compound of ivermectin. Nobel Prize in Medicine 2015.',NULL,19,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Berberine','C20H18NO4',336.3630,'An isoquinoline alkaloid found in Berberis and other plants. It has antimicrobial, anti-inflammatory, antidiabetic, and anticancer properties. Activates AMPK and is used in traditional Chinese and Ayurvedic medicine.',NULL,NULL,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Colchicine','C22H25NO6',399.4370,'A toxic alkaloid extracted from Colchicum autumnale (autumn crocus). It inhibits microtubule polymerization by binding to tubulin. Used clinically to treat gout and familial Mediterranean fever.',NULL,NULL,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Lycopene','C40H56',536.8720,'A bright red carotenoid pigment found in tomatoes and other red fruits. A powerful antioxidant that neutralizes free radicals. Associated with reduced risk of prostate cancer and cardiovascular disease.',NULL,NULL,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Beta-Carotene','C40H56',536.8720,'A strongly colored red-orange pigment abundant in plants and fruits. A precursor to vitamin A (retinol) in the human body. Essential for vision, immune function, and skin health.',NULL,NULL,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Thymoquinone','C10H12O2',164.2010,'The most bioactive compound isolated from Nigella sativa (black seed) oil. It exhibits anti-inflammatory, antioxidant, anticancer, and antimicrobial properties. Used in traditional Islamic medicine for over 2000 years.',NULL,NULL,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Ursolic Acid','C30H48O3',456.7000,'A pentacyclic triterpenoid found in the waxy coatings of many fruits and herbs including apple peel, rosemary, and basil. Has anti-inflammatory, antitumor, antiviral, and hepatoprotective activities. Also promotes muscle growth.',NULL,NULL,1,1);
INSERT INTO `compounds` (`name`,`formula`,`molecular_weight`,`description`,`structure_image`,`organism_id`,`created_by`,`version`) VALUES ('Naringenin','C15H12O5',272.2530,'A flavanone found abundantly in citrus fruits, particularly grapefruit. Has antioxidant, anti-inflammatory, antifungal, and anticancer properties. Inhibits CYP3A4 enzymes, affecting the metabolism of many drugs.',NULL,NULL,1,1);

-- COMPOUND_REFERENCE (4 records)
INSERT INTO `compound_reference` (`compound_id`,`reference_id`) VALUES (1,1);
INSERT INTO `compound_reference` (`compound_id`,`reference_id`) VALUES (2,2);
INSERT INTO `compound_reference` (`compound_id`,`reference_id`) VALUES (3,3);
INSERT INTO `compound_reference` (`compound_id`,`reference_id`) VALUES (5,4);

